### ISSUE TITLE
Invalid memory address or nil pointer dereference on server.Finish()

### ISSUE THREAD

**Issue by Robinnnnn** [adams-sarah/test2doc#10]
All of my tests in a single `main_test.go` file at the root of my project. They run cleanly until the very end, when I get this error:

```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a4cea]

goroutine 1 [running]:
panic(0x5846e0, 0xc42000c0e0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/adams-sarah/test2doc/test.(*Server).Finish(0x0)
        /Users/robinkim/irisvr/irisvr_go/src/github.com/adams-sarah/test2doc/test/server.go:42 +0x3a
irv_orgs.TestMain(0xc42637fee8)
        /Users/robinkim/irisvr/irisvr_go/src/irv_orgs/main_test.go:31 +0x4f
main.main()
```

I'm using gorilla mux and have set up my tests as follows:

```go
var server *test.Server

func TestMain(m *testing.M) {
	setup()
	tests := m.Run()
	DropDatabase()
	server.Finish()  // <--- fails here
	os.Exit(tests)
}

func setup() {
	...
	test.RegisterURLVarExtractor(mux.Vars)
	server, err := test.NewServer(routes)
	if err != nil {
		panic(err.Error())
	}
	...
}
```

**Comment by Robinnnnn** [comment]
**UPDATE**

According to the stack trace, the finish command fails at this line: https://github.com/adams-sarah/test2doc/blob/master/test/server.go#L42

It says that the `s *Server` argument is `<nil>`. Will continue digging.

**Comment by adams-sarah** [comment]
@Robinnnnn 

this is because you are instantiating a new `server` variable in setup(). So your package-level `server` variable at the top is never being set.

Your setup func should instead read:

```go
	test.RegisterURLVarExtractor(mux.Vars)
	var err error
	server, err = test.NewServer(routes)
	if err != nil {
		panic(err.Error())
	}
```

**Comment by Robinnnnn** [comment]
You're right, my bad about that
